//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Viopack_ErpEntities : DbContext
    {
        public Viopack_ErpEntities()
            : base("name=Viopack_ErpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_arac> tbl_arac { get; set; }
        public virtual DbSet<tbl_firm> tbl_firm { get; set; }
        public virtual DbSet<tbl_firma> tbl_firma { get; set; }
        public virtual DbSet<tbl_firma_firma> tbl_firma_firma { get; set; }
        public virtual DbSet<tbl_firma_gorusmeler> tbl_firma_gorusmeler { get; set; }
        public virtual DbSet<tbl_firma_teslimat> tbl_firma_teslimat { get; set; }
        public virtual DbSet<tbl_firma_teslimat_etiket> tbl_firma_teslimat_etiket { get; set; }
        public virtual DbSet<tbl_sektor> tbl_sektor { get; set; }
        public virtual DbSet<tbl_sevkiyat> tbl_sevkiyat { get; set; }
        public virtual DbSet<tbl_Tanim> tbl_Tanim { get; set; }
        public virtual DbSet<tbl_ulke> tbl_ulke { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_anilox> tbl_anilox { get; set; }
        public virtual DbSet<tbl_bakim> tbl_bakim { get; set; }
        public virtual DbSet<tbl_baski_tip> tbl_baski_tip { get; set; }
        public virtual DbSet<tbl_baski_tip_detay> tbl_baski_tip_detay { get; set; }
        public virtual DbSet<tbl_bicak> tbl_bicak { get; set; }
        public virtual DbSet<tbl_bicak_disli> tbl_bicak_disli { get; set; }
        public virtual DbSet<tbl_bicak_iz> tbl_bicak_iz { get; set; }
        public virtual DbSet<tbl_bicak_makina> tbl_bicak_makina { get; set; }
        public virtual DbSet<tbl_bicak_sebep> tbl_bicak_sebep { get; set; }
        public virtual DbSet<tbl_bicak_sekil> tbl_bicak_sekil { get; set; }
        public virtual DbSet<tbl_bicak_tip> tbl_bicak_tip { get; set; }
        public virtual DbSet<tbl_bicak_yenileme> tbl_bicak_yenileme { get; set; }
        public virtual DbSet<tbl_birim> tbl_birim { get; set; }
        public virtual DbSet<tbl_carpan> tbl_carpan { get; set; }
        public virtual DbSet<tbl_degisen> tbl_degisen { get; set; }
        public virtual DbSet<tbl_depo> tbl_depo { get; set; }
        public virtual DbSet<tbl_depo_firma> tbl_depo_firma { get; set; }
        public virtual DbSet<tbl_dilim> tbl_dilim { get; set; }
        public virtual DbSet<tbl_dilim_gecici> tbl_dilim_gecici { get; set; }
        public virtual DbSet<tbl_dilim_gecici1> tbl_dilim_gecici1 { get; set; }
        public virtual DbSet<tbl_disli_hesap> tbl_disli_hesap { get; set; }
        public virtual DbSet<tbl_dof> tbl_dof { get; set; }
        public virtual DbSet<tbl_dof_dagitim> tbl_dof_dagitim { get; set; }
        public virtual DbSet<tbl_dof_grup> tbl_dof_grup { get; set; }
        public virtual DbSet<tbl_dof_personel> tbl_dof_personel { get; set; }
        public virtual DbSet<tbl_dof_tip> tbl_dof_tip { get; set; }
        public virtual DbSet<tbl_doviz> tbl_doviz { get; set; }
        public virtual DbSet<tbl_doviz_kur> tbl_doviz_kur { get; set; }
        public virtual DbSet<tbl_durum> tbl_durum { get; set; }
        public virtual DbSet<tbl_durum_firma> tbl_durum_firma { get; set; }
        public virtual DbSet<tbl_durum_teklif> tbl_durum_teklif { get; set; }
        public virtual DbSet<tbl_ekstragider_tip> tbl_ekstragider_tip { get; set; }
        public virtual DbSet<tbl_fire_islem> tbl_fire_islem { get; set; }
        public virtual DbSet<tbl_fire_makina> tbl_fire_makina { get; set; }
        public virtual DbSet<tbl_firma_durum> tbl_firma_durum { get; set; }
        public virtual DbSet<tbl_firma_kontakt> tbl_firma_kontakt { get; set; }
        public virtual DbSet<tbl_firma_kontakt_cocuk> tbl_firma_kontakt_cocuk { get; set; }
        public virtual DbSet<tbl_firma_personel> tbl_firma_personel { get; set; }
        public virtual DbSet<tbl_genel> tbl_genel { get; set; }
        public virtual DbSet<tbl_gerceklesen_satis> tbl_gerceklesen_satis { get; set; }
        public virtual DbSet<tbl_gider> tbl_gider { get; set; }
        public virtual DbSet<tbl_gorusme_teknik> tbl_gorusme_teknik { get; set; }
        public virtual DbSet<tbl_gorusme_tip> tbl_gorusme_tip { get; set; }
        public virtual DbSet<tbl_grafik> tbl_grafik { get; set; }
        public virtual DbSet<tbl_grafik_durum> tbl_grafik_durum { get; set; }
        public virtual DbSet<tbl_grafik_islem> tbl_grafik_islem { get; set; }
        public virtual DbSet<tbl_grafik_onay> tbl_grafik_onay { get; set; }
        public virtual DbSet<tbl_grup> tbl_grup { get; set; }
        public virtual DbSet<tbl_hareket_tip> tbl_hareket_tip { get; set; }
        public virtual DbSet<tbl_hatirlama> tbl_hatirlama { get; set; }
        public virtual DbSet<tbl_hatirlama_personel> tbl_hatirlama_personel { get; set; }
        public virtual DbSet<tbl_il> tbl_il { get; set; }
        public virtual DbSet<tbl_il_ilce> tbl_il_ilce { get; set; }
        public virtual DbSet<tbl_imalatci> tbl_imalatci { get; set; }
        public virtual DbSet<tbl_islem> tbl_islem { get; set; }
        public virtual DbSet<tbl_islem_tip> tbl_islem_tip { get; set; }
        public virtual DbSet<tbl_kalite_ilk> tbl_kalite_ilk { get; set; }
        public virtual DbSet<tbl_kalite_son> tbl_kalite_son { get; set; }
        public virtual DbSet<tbl_klise> tbl_klise { get; set; }
        public virtual DbSet<tbl_klise_alt> tbl_klise_alt { get; set; }
        public virtual DbSet<tbl_klise_ebad> tbl_klise_ebad { get; set; }
        public virtual DbSet<tbl_klise_film> tbl_klise_film { get; set; }
        public virtual DbSet<tbl_klise_gonderme> tbl_klise_gonderme { get; set; }
        public virtual DbSet<tbl_klise_pantone> tbl_klise_pantone { get; set; }
        public virtual DbSet<tbl_klise_revizyon> tbl_klise_revizyon { get; set; }
        public virtual DbSet<tbl_klise_revizyon_sebep> tbl_klise_revizyon_sebep { get; set; }
        public virtual DbSet<tbl_klise_sabagkod> tbl_klise_sabagkod { get; set; }
        public virtual DbSet<tbl_klise_saklama> tbl_klise_saklama { get; set; }
        public virtual DbSet<tbl_klise_sebep> tbl_klise_sebep { get; set; }
        public virtual DbSet<tbl_klise_takim> tbl_klise_takim { get; set; }
        public virtual DbSet<tbl_klise_tip> tbl_klise_tip { get; set; }
        public virtual DbSet<tbl_klise_uyum> tbl_klise_uyum { get; set; }
        public virtual DbSet<tbl_klise_yenileme> tbl_klise_yenileme { get; set; }
        public virtual DbSet<tbl_konsinye> tbl_konsinye { get; set; }
        public virtual DbSet<tbl_kullanimalani> tbl_kullanimalani { get; set; }
        public virtual DbSet<tbl_makina_bakim> tbl_makina_bakim { get; set; }
        public virtual DbSet<tbl_makina_bakim_hareket> tbl_makina_bakim_hareket { get; set; }
        public virtual DbSet<tbl_makina_bicaktip> tbl_makina_bicaktip { get; set; }
        public virtual DbSet<tbl_makina_birim> tbl_makina_birim { get; set; }
        public virtual DbSet<tbl_makina_calisma> tbl_makina_calisma { get; set; }
        public virtual DbSet<tbl_makina_calisma_hafta> tbl_makina_calisma_hafta { get; set; }
        public virtual DbSet<tbl_makina_disli> tbl_makina_disli { get; set; }
        public virtual DbSet<tbl_makina_gider> tbl_makina_gider { get; set; }
        public virtual DbSet<tbl_makina_gider_grup> tbl_makina_gider_grup { get; set; }
        public virtual DbSet<tbl_makina_grup> tbl_makina_grup { get; set; }
        public virtual DbSet<tbl_makina_islem> tbl_makina_islem { get; set; }
        public virtual DbSet<tbl_makina_islem_urun> tbl_makina_islem_urun { get; set; }
        public virtual DbSet<tbl_makina_kart> tbl_makina_kart { get; set; }
        public virtual DbSet<tbl_maliyet> tbl_maliyet { get; set; }
        public virtual DbSet<tbl_maliyet_adet> tbl_maliyet_adet { get; set; }
        public virtual DbSet<tbl_maliyet_carpan> tbl_maliyet_carpan { get; set; }
        public virtual DbSet<tbl_maliyet_indirim> tbl_maliyet_indirim { get; set; }
        public virtual DbSet<tbl_maliyet_islem> tbl_maliyet_islem { get; set; }
        public virtual DbSet<tbl_maliyet_islem_urun> tbl_maliyet_islem_urun { get; set; }
        public virtual DbSet<tbl_maliyet_islem_zorunlu> tbl_maliyet_islem_zorunlu { get; set; }
        public virtual DbSet<tbl_maliyet_lf> tbl_maliyet_lf { get; set; }
        public virtual DbSet<tbl_maliyet_malzeme> tbl_maliyet_malzeme { get; set; }
        public virtual DbSet<tbl_maliyet_onay> tbl_maliyet_onay { get; set; }
        public virtual DbSet<tbl_maliyet_sabit> tbl_maliyet_sabit { get; set; }
        public virtual DbSet<tbl_mamul_tip> tbl_mamul_tip { get; set; }
        public virtual DbSet<tbl_mamul_tip_hat> tbl_mamul_tip_hat { get; set; }
        public virtual DbSet<tbl_muadil> tbl_muadil { get; set; }
        public virtual DbSet<tbl_odeme> tbl_odeme { get; set; }
        public virtual DbSet<tbl_opaklik> tbl_opaklik { get; set; }
        public virtual DbSet<tbl_parametre> tbl_parametre { get; set; }
        public virtual DbSet<tbl_parlaklik> tbl_parlaklik { get; set; }
        public virtual DbSet<tbl_personel> tbl_personel { get; set; }
        public virtual DbSet<tbl_personel_bilgisayar> tbl_personel_bilgisayar { get; set; }
        public virtual DbSet<tbl_personel_ceza> tbl_personel_ceza { get; set; }
        public virtual DbSet<tbl_personel_dil> tbl_personel_dil { get; set; }
        public virtual DbSet<tbl_personel_egitim> tbl_personel_egitim { get; set; }
        public virtual DbSet<tbl_personel_egitim_personel> tbl_personel_egitim_personel { get; set; }
        public virtual DbSet<tbl_personel_eposta> tbl_personel_eposta { get; set; }
        public virtual DbSet<tbl_personel_firm> tbl_personel_firm { get; set; }
        public virtual DbSet<tbl_personel_grup> tbl_personel_grup { get; set; }
        public virtual DbSet<tbl_personel_ihtiyac> tbl_personel_ihtiyac { get; set; }
        public virtual DbSet<tbl_personel_islem> tbl_personel_islem { get; set; }
        public virtual DbSet<tbl_personel_izin> tbl_personel_izin { get; set; }
        public virtual DbSet<tbl_personel_izin_hak> tbl_personel_izin_hak { get; set; }
        public virtual DbSet<tbl_personel_kart> tbl_personel_kart { get; set; }
        public virtual DbSet<tbl_personel_kurs> tbl_personel_kurs { get; set; }
        public virtual DbSet<tbl_personel_makina> tbl_personel_makina { get; set; }
        public virtual DbSet<tbl_personel_makina_grup> tbl_personel_makina_grup { get; set; }
        public virtual DbSet<tbl_personel_saglik> tbl_personel_saglik { get; set; }
        public virtual DbSet<tbl_randevu> tbl_randevu { get; set; }
        public virtual DbSet<tbl_sa_istek> tbl_sa_istek { get; set; }
        public virtual DbSet<tbl_sa_siparis> tbl_sa_siparis { get; set; }
        public virtual DbSet<tbl_sa_siparis_klise> tbl_sa_siparis_klise { get; set; }
        public virtual DbSet<tbl_sa_siparis_siparis> tbl_sa_siparis_siparis { get; set; }
        public virtual DbSet<tbl_sa_siparis_teslim> tbl_sa_siparis_teslim { get; set; }
        public virtual DbSet<tbl_sa_siparis_teslim_detay> tbl_sa_siparis_teslim_detay { get; set; }
        public virtual DbSet<tbl_sa_teklif> tbl_sa_teklif { get; set; }
        public virtual DbSet<tbl_sa_teklif_fiyat> tbl_sa_teklif_fiyat { get; set; }
        public virtual DbSet<tbl_sabagkod> tbl_sabagkod { get; set; }
        public virtual DbSet<tbl_sevk> tbl_sevk { get; set; }
        public virtual DbSet<tbl_sevk_alt> tbl_sevk_alt { get; set; }
        public virtual DbSet<tbl_sevk_detay> tbl_sevk_detay { get; set; }
        public virtual DbSet<tbl_sevk_tip> tbl_sevk_tip { get; set; }
        public virtual DbSet<tbl_sikayet_gelen> tbl_sikayet_gelen { get; set; }
        public virtual DbSet<tbl_sikayet_gelen_tip> tbl_sikayet_gelen_tip { get; set; }
        public virtual DbSet<tbl_sikayet_hareket> tbl_sikayet_hareket { get; set; }
        public virtual DbSet<tbl_sikayet_personel> tbl_sikayet_personel { get; set; }
        public virtual DbSet<tbl_sikayet_sikayet_tip> tbl_sikayet_sikayet_tip { get; set; }
        public virtual DbSet<tbl_sikayet_tutar> tbl_sikayet_tutar { get; set; }
        public virtual DbSet<tbl_siparis> tbl_siparis { get; set; }
        public virtual DbSet<tbl_siparis_amb> tbl_siparis_amb { get; set; }
        public virtual DbSet<tbl_siparis_degisiklik> tbl_siparis_degisiklik { get; set; }
        public virtual DbSet<tbl_siparis_ekstragider> tbl_siparis_ekstragider { get; set; }
        public virtual DbSet<tbl_siparis_gider> tbl_siparis_gider { get; set; }
        public virtual DbSet<tbl_siparis_hareket> tbl_siparis_hareket { get; set; }
        public virtual DbSet<tbl_siparis_ihtiyac> tbl_siparis_ihtiyac { get; set; }
        public virtual DbSet<tbl_siparis_islem> tbl_siparis_islem { get; set; }
        public virtual DbSet<tbl_siparis_klise> tbl_siparis_klise { get; set; }
        public virtual DbSet<tbl_siparis_klise_alt> tbl_siparis_klise_alt { get; set; }
        public virtual DbSet<tbl_siparis_klise_pantone> tbl_siparis_klise_pantone { get; set; }
        public virtual DbSet<tbl_siparis_mak> tbl_siparis_mak { get; set; }
        public virtual DbSet<tbl_siparis_makina> tbl_siparis_makina { get; set; }
        public virtual DbSet<tbl_siparis_onay> tbl_siparis_onay { get; set; }
        public virtual DbSet<tbl_siparis_onay_adres> tbl_siparis_onay_adres { get; set; }
        public virtual DbSet<tbl_siparis_termin> tbl_siparis_termin { get; set; }
        public virtual DbSet<tbl_siparis_teslim> tbl_siparis_teslim { get; set; }
        public virtual DbSet<tbl_siparis_teslim2> tbl_siparis_teslim2 { get; set; }
        public virtual DbSet<tbl_tasiyici> tbl_tasiyici { get; set; }
        public virtual DbSet<tbl_teklif> tbl_teklif { get; set; }
        public virtual DbSet<tbl_teklif_fiyat> tbl_teklif_fiyat { get; set; }
        public virtual DbSet<tbl_teklif_gonder> tbl_teklif_gonder { get; set; }
        public virtual DbSet<tbl_teklif_gonder_sonuc> tbl_teklif_gonder_sonuc { get; set; }
        public virtual DbSet<tbl_teklif_sira> tbl_teklif_sira { get; set; }
        public virtual DbSet<tbl_teknik_ortam> tbl_teknik_ortam { get; set; }
        public virtual DbSet<tbl_teknik_pantone> tbl_teknik_pantone { get; set; }
        public virtual DbSet<tbl_teknik_yuzey> tbl_teknik_yuzey { get; set; }
        public virtual DbSet<tbl_teslimat> tbl_teslimat { get; set; }
        public virtual DbSet<tbl_test> tbl_test { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
        public virtual DbSet<tbl_urun_agirlik> tbl_urun_agirlik { get; set; }
        public virtual DbSet<tbl_urun_ambalaji> tbl_urun_ambalaji { get; set; }
        public virtual DbSet<tbl_urun_birim> tbl_urun_birim { get; set; }
        public virtual DbSet<tbl_urun_ekbicak> tbl_urun_ekbicak { get; set; }
        public virtual DbSet<tbl_urun_fire> tbl_urun_fire { get; set; }
        public virtual DbSet<tbl_urun_firma> tbl_urun_firma { get; set; }
        public virtual DbSet<tbl_urun_hareket> tbl_urun_hareket { get; set; }
        public virtual DbSet<tbl_urun_ihtiyac> tbl_urun_ihtiyac { get; set; }
        public virtual DbSet<tbl_urun_kk> tbl_urun_kk { get; set; }
        public virtual DbSet<tbl_urun_lf> tbl_urun_lf { get; set; }
        public virtual DbSet<tbl_urun_makina> tbl_urun_makina { get; set; }
        public virtual DbSet<tbl_urun_malzeme> tbl_urun_malzeme { get; set; }
        public virtual DbSet<tbl_urun_mamul_tip> tbl_urun_mamul_tip { get; set; }
        public virtual DbSet<tbl_urun_resim> tbl_urun_resim { get; set; }
        public virtual DbSet<tbl_urun_revizyon> tbl_urun_revizyon { get; set; }
        public virtual DbSet<tbl_urun_sevk> tbl_urun_sevk { get; set; }
        public virtual DbSet<tbl_urun_sevk_detay> tbl_urun_sevk_detay { get; set; }
        public virtual DbSet<tbl_urun_sevk_detay_alt> tbl_urun_sevk_detay_alt { get; set; }
        public virtual DbSet<tbl_urun_stokkart> tbl_urun_stokkart { get; set; }
        public virtual DbSet<tbl_urun_stokkart_iade> tbl_urun_stokkart_iade { get; set; }
        public virtual DbSet<tbl_urun_stokkart_siparis> tbl_urun_stokkart_siparis { get; set; }
        public virtual DbSet<tbl_urun_tavsiye_en> tbl_urun_tavsiye_en { get; set; }
        public virtual DbSet<tbl_urun_tip> tbl_urun_tip { get; set; }
        public virtual DbSet<tbl_vardiya> tbl_vardiya { get; set; }
        public virtual DbSet<tbl_vardiya_bicak> tbl_vardiya_bicak { get; set; }
        public virtual DbSet<tbl_vardiya_hareket> tbl_vardiya_hareket { get; set; }
        public virtual DbSet<tbl_vardiya_urun> tbl_vardiya_urun { get; set; }
        public virtual DbSet<tbl_vardiya_urun_detay> tbl_vardiya_urun_detay { get; set; }
        public virtual DbSet<tbl_vardiya_urun_fire> tbl_vardiya_urun_fire { get; set; }
        public virtual DbSet<tbl_vardiya_zaman> tbl_vardiya_zaman { get; set; }
        public virtual DbSet<tbl_vardiya_zaman_fire> tbl_vardiya_zaman_fire { get; set; }
        public virtual DbSet<tbl_versiyon> tbl_versiyon { get; set; }
        public virtual DbSet<tbl_yapisal1> tbl_yapisal1 { get; set; }
        public virtual DbSet<tbl_yapisal2> tbl_yapisal2 { get; set; }
        public virtual DbSet<tbl_yapisal3> tbl_yapisal3 { get; set; }
        public virtual DbSet<tbl_yapiskan> tbl_yapiskan { get; set; }
        public virtual DbSet<tbl_yarimamulkod> tbl_yarimamulkod { get; set; }
        public virtual DbSet<tbl_zaman_fire> tbl_zaman_fire { get; set; }
    }
}
