//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_doviz_kur
    {
        public System.DateTime tarih { get; set; }
        public string dovizkod { get; set; }
        public Nullable<double> dovizalisf { get; set; }
        public Nullable<double> dovizsatisf { get; set; }
        public Nullable<double> efektifalisf1 { get; set; }
        public Nullable<double> efektifsatisf1 { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
