//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_bakim
    {
        public int bakimno { get; set; }
        public string bakimkod { get; set; }
        public string makinakodu { get; set; }
        public string talepeden { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public Nullable<System.DateTime> baslatarih { get; set; }
        public Nullable<System.DateTime> baslasaat { get; set; }
        public Nullable<System.DateTime> bitistarih { get; set; }
        public Nullable<System.DateTime> bitissaat { get; set; }
        public string aciliyet { get; set; }
        public string durumu { get; set; }
        public string uretimdurdu { get; set; }
        public string arizatanimi { get; set; }
        public string bakimtanimi { get; set; }
        public int hareketno { get; set; }
        public string sonuc { get; set; }
        public string bakimiyapan { get; set; }
        public short sure { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
