//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_teklif_fiyat
    {
        public int sateklifkod { get; set; }
        public string sirano { get; set; }
        public Nullable<double> ustmiktar { get; set; }
        public Nullable<double> netmiktar { get; set; }
        public Nullable<double> altmiktar { get; set; }
        public string birimkod { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
    }
}
