//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_sabit
    {
        public Nullable<float> vadevalor { get; set; }
        public Nullable<float> onaylicarpan { get; set; }
        public Nullable<float> bobin { get; set; }
        public Nullable<float> bobinfire { get; set; }
        public Nullable<int> sonhareketno { get; set; }
        public Nullable<float> saonay { get; set; }
        public Nullable<byte> gorusmehafta { get; set; }
        public double yonetimgideri { get; set; }
        public double yonetimgiderigercek { get; set; }
    }
}
