//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_adet
    {
        public int maliyetkodu { get; set; }
        public double adet { get; set; }
        public double minadet { get; set; }
        public double maxadet { get; set; }
        public double carpannet { get; set; }
        public double carpan { get; set; }
        public double fiyat { get; set; }
        public string birimkod { get; set; }
        public string teklifbirimi { get; set; }
        public double fire { get; set; }
        public double artifire { get; set; }
        public double makinagider { get; set; }
        public double elektirkgider { get; set; }
        public double iscilikgider { get; set; }
        public double amortismangider { get; set; }
        public double sarfmalzemefiyat { get; set; }
        public double yardhammaddetutar { get; set; }
        public double hammaddetutar { get; set; }
        public double islemtutar { get; set; }
        public double nakliyetutar { get; set; }
        public double yonetimgider { get; set; }
        public double yonetimgidernet { get; set; }
        public bool toplamfiyat { get; set; }
        public double toplamfiyattutar { get; set; }
        public short vade { get; set; }
        public double uzunluk { get; set; }
        public double birimalanfiyat { get; set; }
        public double birimagirlikfiyat { get; set; }
        public double birimadetfiyat { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
