//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_hareket
    {
        public long hareketid { get; set; }
        public int hareketno { get; set; }
        public string stokkod { get; set; }
        public string urunkod { get; set; }
        public string harekettipkod { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
        public double cikismiktar1 { get; set; }
        public double cikismiktar2 { get; set; }
        public int cikistabaka { get; set; }
        public double netcikis { get; set; }
        public Nullable<System.DateTime> giristarih { get; set; }
        public double girismiktar1 { get; set; }
        public double girismiktar2 { get; set; }
        public int giristabaka { get; set; }
        public double netgiris { get; set; }
        public bool muadil { get; set; }
        public string muadilurunkod { get; set; }
        public string fisno { get; set; }
        public string irsaliyeno { get; set; }
        public Nullable<System.DateTime> irsaliyetarih { get; set; }
        public string aciklama { get; set; }
        public int revizesiparisno { get; set; }
        public bool kullanildi { get; set; }
        public long belgeno { get; set; }
        public long terminno { get; set; }
        public long said { get; set; }
        public int sasiparisno { get; set; }
        public string sira { get; set; }
        public int teslimno { get; set; }
        public int sevkiyatno { get; set; }
        public short yyadet { get; set; }
        public double idealen { get; set; }
        public long satirdetayid { get; set; }
        public long sipihtiyacid { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
