//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel
    {
        public string personelkodu { get; set; }
        public string adisoyadi { get; set; }
        public string password { get; set; }
        public string sup { get; set; }
        public string maliyetonay { get; set; }
        public string sorunlufirma { get; set; }
        public string grafikonay { get; set; }
        public string uretimonay { get; set; }
        public string mnu01_00 { get; set; }
        public string mnu01_01 { get; set; }
        public string mnu01_02 { get; set; }
        public string mnu01_03 { get; set; }
        public string mnu02_00 { get; set; }
        public string mnu02_01 { get; set; }
        public string mnu02_02 { get; set; }
        public string mnu02_03 { get; set; }
        public string mnu02_04 { get; set; }
        public string mnu02_05 { get; set; }
        public string mnu03_00 { get; set; }
        public string mnu03_01 { get; set; }
        public string mnu03_02 { get; set; }
        public string mnu04_00 { get; set; }
        public string mnu04_01 { get; set; }
        public string mnu04_02 { get; set; }
        public string mnu04_03 { get; set; }
        public string mnu05_00 { get; set; }
        public string mnu05_01 { get; set; }
        public string mnu05_02 { get; set; }
        public string mnu05_03 { get; set; }
        public string mnu06_00 { get; set; }
        public string mnu07_00 { get; set; }
        public string mnu07_01 { get; set; }
        public string mnu08_00 { get; set; }
        public string mnu08_01 { get; set; }
        public string mnu08_02 { get; set; }
        public string mnu08_02_01 { get; set; }
        public string mnu08_02_02 { get; set; }
        public string mnu08_03 { get; set; }
        public string mnu08_03_01 { get; set; }
        public string mnu08_03_02 { get; set; }
        public string mnu08_04 { get; set; }
        public string mnu09_00 { get; set; }
        public string mnu09_01 { get; set; }
        public string mnu09_01_01 { get; set; }
        public string mnu09_01_02 { get; set; }
        public string mnu09_01_03 { get; set; }
        public string mnu09_01_04 { get; set; }
        public string mnu09_02 { get; set; }
        public string mnu09_02_01 { get; set; }
        public string mnu09_02_02 { get; set; }
        public string mnu09_02_03 { get; set; }
        public string mnu09_02_04 { get; set; }
        public string mnu09_02_05 { get; set; }
        public string mnu09_03 { get; set; }
        public string mnu09_03_01 { get; set; }
        public string mnu09_03_02 { get; set; }
        public string mnu09_03_03 { get; set; }
        public string mnu09_04 { get; set; }
        public string mnu10_00 { get; set; }
        public string mnu10_01 { get; set; }
        public string mnu10_01_01 { get; set; }
        public string mnu10_01_02 { get; set; }
        public string mnu10_01_03 { get; set; }
        public string mnu10_01_04 { get; set; }
        public string mnu10_02 { get; set; }
        public string mnu10_02_01 { get; set; }
        public string mnu10_02_02 { get; set; }
        public string mnu10_02_03 { get; set; }
        public string mnu10_03 { get; set; }
        public string mnu10_03_01 { get; set; }
        public string mnu10_03_02 { get; set; }
        public string mnu10_03_03 { get; set; }
        public string mnu10_03_04 { get; set; }
        public string mnu10_03_05 { get; set; }
        public string mnu10_03_06 { get; set; }
        public string mnu10_04 { get; set; }
        public string mnu10_04_01 { get; set; }
        public string mnu10_04_02 { get; set; }
        public string mnu10_04_03 { get; set; }
        public string mnu10_04_04 { get; set; }
        public string mnu10_04_05 { get; set; }
        public string mnu10_04_06 { get; set; }
        public string mnu10_04_07 { get; set; }
        public string mnu10_04_08 { get; set; }
        public string mnu10_04_09 { get; set; }
        public string mnu10_05 { get; set; }
        public string mnu10_05_01 { get; set; }
        public string mnu10_05_02 { get; set; }
        public string mnu10_05_03 { get; set; }
        public string mnu10_05_04 { get; set; }
        public string mnu10_05_05 { get; set; }
        public string mnu10_06 { get; set; }
        public string mnu10_06_01 { get; set; }
        public string mnu10_06_02 { get; set; }
        public string mnu10_07 { get; set; }
        public string mnu10_07_01 { get; set; }
        public string mnu10_08 { get; set; }
        public string mnu10_08_01 { get; set; }
        public string mnu10_08_02 { get; set; }
        public string mnu10_08_03 { get; set; }
        public string mnu10_09 { get; set; }
        public string mnu10_09_01 { get; set; }
        public string mnu10_09_02 { get; set; }
        public string mnu10_09_03 { get; set; }
        public string mnu10_09_04 { get; set; }
        public string mnu10_10 { get; set; }
        public string mnu10_10_01 { get; set; }
        public string mnu10_10_02 { get; set; }
        public string mnu10_11 { get; set; }
        public string mnu10_11_01 { get; set; }
        public string mnu10_11_02 { get; set; }
        public string mnu10_12 { get; set; }
        public string mnu10_12_01 { get; set; }
        public string mnu10_12_02 { get; set; }
        public string mnu10_13 { get; set; }
        public string mnu10_14 { get; set; }
        public string mnu10_14_01 { get; set; }
        public string mnu10_14_02 { get; set; }
        public string mnu10_15 { get; set; }
        public string mnu10_15_01 { get; set; }
        public string mnu11_00 { get; set; }
        public string mnu11_01 { get; set; }
        public string mnu06_01 { get; set; }
        public string mnu06_02 { get; set; }
        public string mnu05_04 { get; set; }
        public string mnu02_06 { get; set; }
        public string mnu02_07 { get; set; }
        public string mnu03_03 { get; set; }
        public string mnu01_04 { get; set; }
        public string mnu06_03 { get; set; }
        public string mnu06_04 { get; set; }
    }
}
