//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hatirlama
    {
        public long hatirid { get; set; }
        public long hatirno { get; set; }
        public long gorid { get; set; }
        public string firmakod { get; set; }
        public string kisikod { get; set; }
        public Nullable<bool> kisinin { get; set; }
        public Nullable<bool> cocuk { get; set; }
        public string hatirlama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<short> siklik { get; set; }
        public string siklikadi { get; set; }
        public string gun { get; set; }
        public string hafta { get; set; }
        public string ay { get; set; }
        public string ucay { get; set; }
        public string altiay { get; set; }
        public string yil { get; set; }
        public Nullable<bool> iptal { get; set; }
        public string aciklama { get; set; }
    }
}
