//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sikayet_hareket
    {
        public int hareketID { get; set; }
        public int sikayetno { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> anasikayet { get; set; }
        public string hareketadi { get; set; }
        public string hareketno { get; set; }
        public string aciklama { get; set; }
        public Nullable<double> hareketmiktar { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
