//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dof_tip
    {
        public string dofkod { get; set; }
        public string tipkod { get; set; }
        public string aciklama { get; set; }
        public string nedeneylem { get; set; }
    }
}
