//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teklif_sira
    {
        public long teklifsiraid { get; set; }
        public long kodu { get; set; }
        public string sirano { get; set; }
        public long maliyetkodu { get; set; }
        public double klisemasraf { get; set; }
        public string kdovizkod { get; set; }
        public double bicakmasraf { get; set; }
        public string bdovizkod { get; set; }
        public string uruntipkod { get; set; }
        public bool teklifonay { get; set; }
        public string urunnot { get; set; }
        public string urunnot2 { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
