//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_ceza
    {
        public int cezaid { get; set; }
        public string personelkodu { get; set; }
        public string adi { get; set; }
        public Nullable<bool> ceza { get; set; }
        public string sebep { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
