//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dof_personel
    {
        public string dofkod { get; set; }
        public string personel { get; set; }
        public string personelkodu { get; set; }
        public string firmakod { get; set; }
        public string kisikod { get; set; }
    }
}
