//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_ihtiyac
    {
        public long sipihtiyacid { get; set; }
        public long urunihtiyacid { get; set; }
        public int siparisno { get; set; }
        public string urunkod { get; set; }
        public double miktar { get; set; }
        public string birimkod { get; set; }
        public string birim { get; set; }
        public double en { get; set; }
        public bool hammadde { get; set; }
        public string islemkod { get; set; }
        public bool fason { get; set; }
        public double fire { get; set; }
        public string ihtiyactakip { get; set; }
        public string ihtiyacnotu { get; set; }
    }
}
