//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_gorusmeler
    {
        public long gorid { get; set; }
        public string firmakod { get; set; }
        public short gorusmeno { get; set; }
        public int teknikno { get; set; }
        public Nullable<System.DateTime> gorusmetarihi { get; set; }
        public string gorusmetipno { get; set; }
        public string kisikod { get; set; }
        public string personelkodu { get; set; }
        public string gorusmenotu { get; set; }
        public bool gorusmebitti { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    
        public virtual tbl_firma tbl_firma { get; set; }
    }
}
