//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_baski_tip_detay
    {
        public long baskitipaltID { get; set; }
        public string baskitipkod { get; set; }
        public int mamultipkod { get; set; }
        public double azyogunluk { get; set; }
        public double cokyogunluk { get; set; }
    }
}
