//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teklif
    {
        public long kodu { get; set; }
        public int gonderno { get; set; }
        public string firmakod { get; set; }
        public System.DateTime tarih { get; set; }
        public string eksartlar { get; set; }
        public string sevkiyatkod { get; set; }
        public string teslimatkod { get; set; }
        public string durumteklifkod { get; set; }
        public string kisikod { get; set; }
        public Nullable<bool> arsiv { get; set; }
        public Nullable<bool> hatirlatma { get; set; }
        public Nullable<System.DateTime> hatirlatmatarih { get; set; }
        public string hatirlatmanot { get; set; }
        public string avans { get; set; }
        public string il { get; set; }
        public string opsiyonkod { get; set; }
        public string personelkodu { get; set; }
        public bool klisegoster { get; set; }
        public double klisemasraf { get; set; }
        public string kdovizkod { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
