//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gorusme_teknik
    {
        public int teknikno { get; set; }
        public string urunadi { get; set; }
        public string musterikod { get; set; }
        public string nasilyapis { get; set; }
        public string rulotabaka { get; set; }
        public short iccap { get; set; }
        public short discap { get; set; }
        public int bobindeadet { get; set; }
        public string akisyonu { get; set; }
        public double tekebadboy { get; set; }
        public double tekebaden { get; set; }
        public double aabosluk { get; set; }
        public double tasiyicien { get; set; }
        public double radus { get; set; }
        public string urunkod { get; set; }
        public string malzemeadi { get; set; }
        public string yapiskan { get; set; }
        public string yapiskanadi { get; set; }
        public bool baskili { get; set; }
        public bool serigafi { get; set; }
        public bool trignomi { get; set; }
        public bool cifttaraf { get; set; }
        public bool lak { get; set; }
        public string yuzey { get; set; }
        public string aylikkulanim { get; set; }
        public string ambalaj { get; set; }
        public string koliadet { get; set; }
        public string ambalajnot { get; set; }
        public string aciklama { get; set; }
        public string rafomru { get; set; }
        public bool degiskenbaski { get; set; }
        public string baskiadi { get; set; }
        public string ozelsart { get; set; }
        public string bicak { get; set; }
        public string olusturanadisoyadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
    }
}
