//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_islem
    {
        public string islemkod { get; set; }
        public string kodaciklama { get; set; }
        public string islemtipkod { get; set; }
        public string baskitipkod { get; set; }
        public string bicaktipkod { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public string fiyatbirim { get; set; }
        public bool yaldiz { get; set; }
        public bool yaldizbaski { get; set; }
        public string bilgi { get; set; }
        public double minalan { get; set; }
        public double maksalan { get; set; }
        public string teklifteyaz { get; set; }
        public string islemaktif { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
