//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sevk_detay
    {
        public long satirdetayid { get; set; }
        public long satirno { get; set; }
        public int siparisno { get; set; }
        public long urunsevkid { get; set; }
        public string musterisano { get; set; }
        public string urunkod { get; set; }
        public short urunno { get; set; }
        public int sevkiyatno { get; set; }
        public string stokkod { get; set; }
        public int koliadet { get; set; }
        public int ruloadet { get; set; }
        public string urunadet { get; set; }
        public double adet { get; set; }
    }
}
