//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_termin
    {
        public long terminid { get; set; }
        public int siparisno { get; set; }
        public double siparismiktar { get; set; }
        public System.DateTime termintarih { get; set; }
        public string firmakod { get; set; }
        public string subekod { get; set; }
        public bool stok { get; set; }
        public short iccap { get; set; }
        public short discap { get; set; }
        public int bobindeadet { get; set; }
        public string bobindebirim { get; set; }
        public string akisyonu { get; set; }
        public short musteriyyadet { get; set; }
        public string sevkiyatkod { get; set; }
        public string terminnot { get; set; }
    }
}
