//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vardiya_hareket
    {
        public int vardiyano { get; set; }
        public int vardiyaaltno { get; set; }
        public string urunkod { get; set; }
        public bool hammadde { get; set; }
        public int hareketno { get; set; }
        public double harcananalan { get; set; }
        public double firealan { get; set; }
        public double harcananalan2 { get; set; }
    }
}
