//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_izin
    {
        public long izinkullanid { get; set; }
        public int izinid { get; set; }
        public string personelkodu { get; set; }
        public System.DateTime cikistarih { get; set; }
        public System.DateTime gelistarih { get; set; }
        public short izingun { get; set; }
        public string aciklama { get; set; }
    }
}
