//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bicak_yenileme
    {
        public string bicakkodu { get; set; }
        public string yenilemeno { get; set; }
        public string serino { get; set; }
        public bool iptal { get; set; }
        public string durumkod { get; set; }
        public string firmakod { get; set; }
        public Nullable<System.DateTime> imaltarihi { get; set; }
        public Nullable<System.DateTime> imhatarihi { get; set; }
        public Nullable<System.DateTime> fiilitarih { get; set; }
        public string bicaksebepkod { get; set; }
        public int tursayisi { get; set; }
        public double fiyat { get; set; }
        public bool kullanimda { get; set; }
        public bool sipariste { get; set; }
        public int sasiparisno { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
    }
}
