//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_klise_ebad
    {
        public string klisekod { get; set; }
        public string calismano { get; set; }
        public Nullable<System.DateTime> calismatarih { get; set; }
        public Nullable<double> tekebadboy { get; set; }
        public Nullable<double> tekebaden { get; set; }
        public Nullable<short> aaadet { get; set; }
        public Nullable<short> yyadet { get; set; }
        public Nullable<double> aabosluk { get; set; }
        public Nullable<double> yybosluk { get; set; }
        public Nullable<short> yybitisikadet { get; set; }
        public string malzemekod { get; set; }
        public Nullable<double> alan { get; set; }
        public string aciklama { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
    }
}
