//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_siparis_teslim
    {
        public long teslimno { get; set; }
        public long said { get; set; }
        public int sasiparisno { get; set; }
        public string sira { get; set; }
        public double teslimmiktar1 { get; set; }
        public double teslimmiktar2 { get; set; }
        public double teslimnetmiktar { get; set; }
        public double teslimkur { get; set; }
        public Nullable<System.DateTime> teslimtarih { get; set; }
        public string irsaliyeno { get; set; }
        public Nullable<System.DateTime> irsaliyetarih { get; set; }
        public int hareketno { get; set; }
        public string faturano { get; set; }
        public Nullable<System.DateTime> faturatarih { get; set; }
        public double faturafiyat { get; set; }
        public bool faturalandi { get; set; }
        public string dovizkod { get; set; }
        public double iskonto { get; set; }
        public Nullable<System.DateTime> kontroltarih { get; set; }
        public string ambalajbutunluk { get; set; }
        public string sevkaraci { get; set; }
        public string paletuygunluk { get; set; }
        public string etiketkontrolu { get; set; }
        public string bobinsarimyonu { get; set; }
        public string korona { get; set; }
        public string yapisma { get; set; }
        public string cekmekontrolu { get; set; }
        public string olcukontrolu { get; set; }
        public string analizsertifikasi { get; set; }
        public string mikronkontolu { get; set; }
        public string kabuldurumu { get; set; }
        public string kontoleden { get; set; }
        public string onayliyan { get; set; }
    }
}
