//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_konsinye
    {
        public int konsinyeno { get; set; }
        public System.DateTime tarih { get; set; }
        public string firmakod { get; set; }
        public string urunkod { get; set; }
        public Nullable<int> siparisno { get; set; }
        public Nullable<int> sevkiyatno { get; set; }
        public string irsaliyeno { get; set; }
        public Nullable<int> koliadet { get; set; }
        public Nullable<int> ruloadet { get; set; }
        public string urunadet { get; set; }
        public Nullable<double> toplamadet { get; set; }
        public Nullable<double> sevkfiyat { get; set; }
        public string faturano { get; set; }
        public Nullable<int> faturakoliadet { get; set; }
        public Nullable<int> faturaruloadet { get; set; }
        public string faturaurunadet { get; set; }
        public Nullable<double> faturatoplamadet { get; set; }
        public Nullable<double> faturafiyat { get; set; }
        public string faturadovizkod { get; set; }
        public Nullable<double> nettoplamadet { get; set; }
        public Nullable<double> iadeadet { get; set; }
        public Nullable<double> geriiadeadet { get; set; }
        public string iadeirsaliyeno { get; set; }
        public Nullable<int> sikayetno { get; set; }
        public string iadenot { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
