//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grafik
    {
        public long grafikno { get; set; }
        public string grafikadi { get; set; }
        public string firmakod { get; set; }
        public string kliseno { get; set; }
        public byte hat { get; set; }
        public string isinsekli { get; set; }
        public Nullable<System.DateTime> baslatarih { get; set; }
        public Nullable<System.DateTime> bitistarih { get; set; }
        public string aciklama { get; set; }
        public string gecikme { get; set; }
        public string grafikdurumkod { get; set; }
        public short netsure { get; set; }
        public int siparisno { get; set; }
        public string urunkod { get; set; }
        public long maliyetkodu { get; set; }
        public string personelkodu { get; set; }
        public string montaj { get; set; }
        public string takip { get; set; }
        public short sirala { get; set; }
        public short siralagrafiker { get; set; }
        public string akisyonu { get; set; }
        public string uygulamasekli { get; set; }
        public string gelenorjinal { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
