//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_islem_zorunlu
    {
        public long maliyetislemZid { get; set; }
        public int maliyetkodu { get; set; }
        public string islemkod { get; set; }
        public string islemtipkod { get; set; }
        public string makinakodu { get; set; }
    }
}
