//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bicak_disli
    {
        public string bicakkodu { get; set; }
        public string dislisayisi { get; set; }
        public string dislisayisi2 { get; set; }
        public Nullable<float> dislidegeri { get; set; }
    }
}
