//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dilim
    {
        public string urunkod { get; set; }
        public string stokkod { get; set; }
        public string stokno { get; set; }
        public string dilmeno { get; set; }
        public double eskimiktar1 { get; set; }
        public Nullable<double> eskimiktar2 { get; set; }
        public double miktar1 { get; set; }
        public Nullable<double> miktar2 { get; set; }
        public string birimkod { get; set; }
        public byte seviye { get; set; }
        public int dilmekod { get; set; }
        public string gideceksiparisno { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
