//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_makina
    {
        public long siparismakinaid { get; set; }
        public int siparisno { get; set; }
        public string makinakodu { get; set; }
        public short sira { get; set; }
        public int siralama { get; set; }
        public short ekgecis { get; set; }
        public bool bitti { get; set; }
        public Nullable<System.DateTime> plantarih { get; set; }
        public int topsetupsure { get; set; }
        public double topislemsure { get; set; }
        public double islemmiktar { get; set; }
        public bool aktif { get; set; }
        public bool sirada { get; set; }
        public string makinabirimkod { get; set; }
        public string uretimnotu { get; set; }
        public bool uretimplanlama { get; set; }
        public string uretimtakip { get; set; }
        public Nullable<System.DateTime> bitistarihi { get; set; }
        public string bitiren { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
    }
}
