//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vardiya_zaman
    {
        public int vardiyano { get; set; }
        public int vardiyaaltno { get; set; }
        public long siparismakinaid { get; set; }
        public System.DateTime baslangicgun { get; set; }
        public Nullable<System.DateTime> baslangicsaat { get; set; }
        public System.DateTime bitisgun { get; set; }
        public Nullable<System.DateTime> bitissaat { get; set; }
        public string sorumlupersonelkodu { get; set; }
        public string personelkodu { get; set; }
        public short netsure { get; set; }
        public string makinakodu { get; set; }
        public short sira { get; set; }
        public double uretimmiktar { get; set; }
        public short bicakyyadet { get; set; }
        public short bicakaaadet { get; set; }
        public double neturetim { get; set; }
        public double uretimmetraj { get; set; }
        public double zamanfiretoplami { get; set; }
        public double urunfirealan { get; set; }
        public double urunalan { get; set; }
        public short yikananunite { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
