//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kalite_ilk
    {
        public long kaliteilkid { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public long teslimno { get; set; }
        public string ambalajbutunluk { get; set; }
        public string sevkaraci { get; set; }
        public string paletuygunluk { get; set; }
        public string etiketkontrolu { get; set; }
        public string bobinsarimyonu { get; set; }
        public string korona { get; set; }
        public string yapisma { get; set; }
        public string cekmekontrolu { get; set; }
        public string olcukontrolu { get; set; }
        public string analizsertifikasi { get; set; }
        public string mikronkontolu { get; set; }
        public string kabuldurumu { get; set; }
        public string kontoleden { get; set; }
        public string onayliyan { get; set; }
    }
}
