//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_parametre
    {
        public string bolum { get; set; }
        public string parametrekod { get; set; }
        public string kodaciklama { get; set; }
        public string veri { get; set; }
        public string bilgisayaradi { get; set; }
    }
}
