//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_istek
    {
        public int istekkod { get; set; }
        public string uruntip { get; set; }
        public Nullable<bool> bicak { get; set; }
        public Nullable<bool> klise { get; set; }
        public string sabagkod { get; set; }
        public string urunadi { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<System.DateTime> termintarih { get; set; }
        public string birimkod { get; set; }
        public Nullable<double> miktar1 { get; set; }
        public Nullable<double> miktar2 { get; set; }
        public Nullable<double> netmiktar { get; set; }
        public string aciklama { get; set; }
        public string personelkodu { get; set; }
        public string istenen { get; set; }
        public string siparisedondu { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
