//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_baski_tip
    {
        public string baskitipkod { get; set; }
        public string kodaciklama { get; set; }
        public double klisefiyat { get; set; }
        public string klisedovizkod { get; set; }
        public string klisefiyatbirim { get; set; }
        public double boyayogunlugu { get; set; }
        public double boyafiyat { get; set; }
        public string boyadovizkod { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
