//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_siparis
    {
        public int said { get; set; }
        public int sasiparisno { get; set; }
        public string sira { get; set; }
        public string sabagkod { get; set; }
        public int istekkod { get; set; }
        public int sateklifkod { get; set; }
        public string uruntipkod { get; set; }
        public string urunkod { get; set; }
        public int siparisno { get; set; }
        public bool bicak { get; set; }
        public string bicakkodu { get; set; }
        public string satipi { get; set; }
        public bool klise { get; set; }
        public string kliseno { get; set; }
        public bool detaysiz { get; set; }
        public string birimkod { get; set; }
        public string urunbirimkod { get; set; }
        public double birimoran { get; set; }
        public double miktar1 { get; set; }
        public double miktar2 { get; set; }
        public int tabaka { get; set; }
        public double netmiktar { get; set; }
        public string kagittipi { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public double tutar { get; set; }
        public double kur { get; set; }
        public double fiyattl { get; set; }
        public double tutartl { get; set; }
        public double vade { get; set; }
        public double kdv { get; set; }
        public Nullable<System.DateTime> siparistarih { get; set; }
        public Nullable<System.DateTime> termintarih { get; set; }
        public string firmakod { get; set; }
        public string firmasiparisno { get; set; }
        public string firmasip { get; set; }
        public string kisikod { get; set; }
        public string aciklama { get; set; }
        public string aciklama2 { get; set; }
        public string yonetimonay { get; set; }
        public string yonetimonay2 { get; set; }
        public string klisefirmakod { get; set; }
        public string klisegondermekod { get; set; }
        public string klisesaklamakod { get; set; }
        public bool kromolin { get; set; }
        public string personelkodu { get; set; }
        public bool numunesivar { get; set; }
        public bool yeniurun { get; set; }
        public Nullable<System.DateTime> gondermetarih { get; set; }
        public bool kontrol_kapat { get; set; }
        public string tasarimci { get; set; }
        public string malzemekodu { get; set; }
        public double en { get; set; }
        public double boy { get; set; }
        public double tekebaden { get; set; }
        public double tekebadboy { get; set; }
        public string tedarikcikodu { get; set; }
        public string tedarikciadi { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
