//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_stokkart_iade
    {
        public int vardiyano { get; set; }
        public int vardiyaaltno { get; set; }
        public string urunkod { get; set; }
        public string stokkod { get; set; }
        public int hareketno { get; set; }
        public double iademiktar1 { get; set; }
        public double iademiktar2 { get; set; }
        public double netiade { get; set; }
        public bool iadealindi { get; set; }
        public Nullable<System.DateTime> iadealinditarih { get; set; }
        public bool etiketbasildi { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
