//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_sevk
    {
        public long urunsevkid { get; set; }
        public string stokkod { get; set; }
        public long siparisno { get; set; }
        public string urunkod { get; set; }
        public short urunno { get; set; }
        public string setmi { get; set; }
        public string takimtek { get; set; }
        public string firmakod { get; set; }
        public string subekod { get; set; }
        public double miktar { get; set; }
        public string sevkedildi { get; set; }
        public Nullable<System.DateTime> sevktaleptarihi { get; set; }
        public int koliadet { get; set; }
        public int ruloadet { get; set; }
        public string urunadet { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public string birimkod { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
