//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_grup
    {
        public string makinagrupkod { get; set; }
        public string kodaciklama { get; set; }
        public short firmId { get; set; }
        public string kalipbilgi { get; set; }
        public short tanimsira { get; set; }
        public string adetforma { get; set; }
        public string uretimdeTakipEt { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
