//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_kurs
    {
        public long kursid { get; set; }
        public string personelkodu { get; set; }
        public string kursadi { get; set; }
        public string yer { get; set; }
        public string sure { get; set; }
    }
}
