//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_egitim
    {
        public int personelEgitimId { get; set; }
        public string personelkodu { get; set; }
        public string verenadi { get; set; }
        public string konu { get; set; }
        public System.DateTime tarih { get; set; }
        public double sure { get; set; }
        public string aciklama { get; set; }
        public bool firmaici { get; set; }
    }
}
