//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_saglik
    {
        public long saglikid { get; set; }
        public string personelkodu { get; set; }
        public System.DateTime tarih { get; set; }
        public string rahatsizlik { get; set; }
        public string bulgu { get; set; }
        public string tani { get; set; }
        public string tedavi { get; set; }
    }
}
