//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_revizyon
    {
        public string urunkod { get; set; }
        public string revizyonkod { get; set; }
        public string alan { get; set; }
        public string eskiveri { get; set; }
        public string yeniveri { get; set; }
        public string desigtirenadisoyadi { get; set; }
        public System.DateTime degistirmetarihi { get; set; }
    }
}
