//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_firma
    {
        public int firmafirmaid { get; set; }
        public string firmakod { get; set; }
        public string firma { get; set; }
        public string alicikod { get; set; }
        public string saticikod { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
        public short firmId { get; set; }
    
        public virtual tbl_firm tbl_firm { get; set; }
        public virtual tbl_firma tbl_firma { get; set; }
    }
}
