//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_teslim
    {
        public int sevkiyatno { get; set; }
        public int siparisno { get; set; }
        public short urunno { get; set; }
        public Nullable<System.DateTime> teslimtarih { get; set; }
        public int koliadet { get; set; }
        public int ruloadet { get; set; }
        public string urunadet { get; set; }
        public double toplamadet { get; set; }
        public bool musteri { get; set; }
        public bool depo { get; set; }
        public bool konsinye { get; set; }
        public bool depodansevk { get; set; }
        public string depokod { get; set; }
        public string firmakod { get; set; }
        public bool sevkedildi { get; set; }
        public string aciklama { get; set; }
        public double koliagirlik { get; set; }
        public double sevkmiktar { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
