//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_klise
    {
        public int siparisno { get; set; }
        public string klisekod { get; set; }
        public string urunkod { get; set; }
        public string pantoneno { get; set; }
        public string kliseuyumkod { get; set; }
        public string formul { get; set; }
        public string aniloxkod { get; set; }
    }
}
