//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_kart
    {
        public string personelkodu { get; set; }
        public bool aktif { get; set; }
        public bool calisiyor { get; set; }
        public string grup { get; set; }
        public bool doviz { get; set; }
        public string grafikyetkili { get; set; }
        public string makinaadi { get; set; }
        public string oturumadi { get; set; }
        public bool sifregir { get; set; }
        public bool hizligir { get; set; }
        public string saonay { get; set; }
        public string saonay2 { get; set; }
        public string firmatemsilcisiatama { get; set; }
        public string personelgrupkod { get; set; }
        public string unvan { get; set; }
        public string sifre2 { get; set; }
        public Nullable<System.DateTime> baslatarih { get; set; }
        public string sosyalno { get; set; }
        public Nullable<System.DateTime> dogumtarih { get; set; }
        public string dogumyeri { get; set; }
        public string medeni { get; set; }
        public string askerlik { get; set; }
        public string ehliyet { get; set; }
        public string kan { get; set; }
        public string adres { get; set; }
        public string ceptelefon { get; set; }
        public string telefon { get; set; }
        public string telefon2 { get; set; }
        public string saglik { get; set; }
        public string aciklama { get; set; }
        public string ilkogretim { get; set; }
        public string ilkyil { get; set; }
        public string lise { get; set; }
        public string liseyil { get; set; }
        public string yuksekokul { get; set; }
        public string yuksekyil { get; set; }
        public string lisansustu { get; set; }
        public string lisansustuyil { get; set; }
        public Nullable<System.DateTime> oryantasyontarih { get; set; }
        public string oryantasyonkisi { get; set; }
        public bool nitelik { get; set; }
        public Nullable<System.DateTime> niteliktarih { get; set; }
        public string niteliknot { get; set; }
        public string foto { get; set; }
        public string eposta { get; set; }
        public string beden { get; set; }
        public string ayakno { get; set; }
        public byte cocuk { get; set; }
        public double maas { get; set; }
        public string bolum { get; set; }
        public int izingun { get; set; }
        public int izinpotansiyel { get; set; }
        public string servis { get; set; }
        public short firmId { get; set; }
        public Nullable<System.DateTime> cikistarih { get; set; }
    }
}
