//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gerceklesen_satis
    {
        public Nullable<System.DateTime> tarih { get; set; }
        public string ay { get; set; }
        public string yil { get; set; }
        public double gerceklesen { get; set; }
        public double fatura { get; set; }
    }
}
