//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vardiya
    {
        public int vardiyano { get; set; }
        public int siparisno { get; set; }
        public string makinakodu { get; set; }
        public double zamanfiretoplami { get; set; }
        public double urunfirealan { get; set; }
        public double urunalan { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
