//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_versiyon
    {
        public int versiyonId { get; set; }
        public string versiyonAd { get; set; }
        public short versiyonmajor { get; set; }
        public short versiyonminor { get; set; }
        public short versiyonrevize { get; set; }
        public System.DateTime versiyontarih { get; set; }
        public string versiyonaciklama { get; set; }
    }
}
