//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_carpan
    {
        public int maliyetkodu { get; set; }
        public double carpan { get; set; }
        public double adet { get; set; }
        public Nullable<int> ek { get; set; }
        public double minadet { get; set; }
        public double maxadet { get; set; }
        public double mlzfiyat { get; set; }
        public double fiyat { get; set; }
        public double fiyatalan { get; set; }
        public double fiyatagirlik { get; set; }
        public double fiyatuzunluk { get; set; }
        public Nullable<double> ttutar { get; set; }
    }
}
