//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_agirlik
    {
        public string urunkod { get; set; }
        public double urunmiktar { get; set; }
        public string birimkod { get; set; }
        public double tekebadboy { get; set; }
        public double tekebaden { get; set; }
        public double tekebadyukseklik { get; set; }
        public double urunagirlik { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
