//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_teklif
    {
        public int sateklifkod { get; set; }
        public string firmakod { get; set; }
        public string sabagkod { get; set; }
        public string uruntipkod { get; set; }
        public string urunkod { get; set; }
        public string bicakkodu { get; set; }
        public Nullable<bool> bicak { get; set; }
        public Nullable<bool> klise { get; set; }
        public Nullable<System.DateTime> baslatarih { get; set; }
        public Nullable<System.DateTime> bitistarih { get; set; }
        public Nullable<short> vade { get; set; }
        public string eksart { get; set; }
        public string teslimatkod { get; set; }
        public string teslimatyeri { get; set; }
        public string sevkiyatkod { get; set; }
        public string ambalaj { get; set; }
        public string odemekod { get; set; }
        public Nullable<byte> garanti { get; set; }
        public string imalatcikod { get; set; }
        public string personelkodu { get; set; }
        public bool iptal { get; set; }
        public string tedarikcikodu { get; set; }
        public string tedarikciadi { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
    }
}
