//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dof
    {
        public string dofkod { get; set; }
        public string doftipi { get; set; }
        public short dofno { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string dfof { get; set; }
        public string firmakod { get; set; }
        public string urunkod { get; set; }
        public int siparisno { get; set; }
        public float miktar { get; set; }
        public string irsaliyeno { get; set; }
        public string tanimi { get; set; }
        public string hatanedenibildirim { get; set; }
        public string hatanedeni { get; set; }
        public string eylembildirim { get; set; }
        public string eylem { get; set; }
        public string eylemplanlama { get; set; }
        public Nullable<System.DateTime> sevktarihi { get; set; }
        public string raporno { get; set; }
        public string acanpersonel { get; set; }
        public string acankisi { get; set; }
        public string acanbolum { get; set; }
        public string ilgilikisi { get; set; }
        public string ilgilibolum { get; set; }
        public bool kontrol_kapat { get; set; }
        public System.DateTime kapattarih { get; set; }
        public string kapatankisi { get; set; }
        public string sonuc { get; set; }
        public bool dfgerekli { get; set; }
        public string dfno { get; set; }
        public string onayliyankisi { get; set; }
        public System.DateTime onaytarih { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
