//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_kontakt
    {
        public string firmakod { get; set; }
        public string kisikod { get; set; }
        public string ad { get; set; }
        public string iptalet { get; set; }
        public string departman { get; set; }
        public string gorevi { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public string hobiler { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string postakod { get; set; }
        public string ilcekod { get; set; }
        public string ilkod { get; set; }
        public string ulkekod { get; set; }
        public string telefon1 { get; set; }
        public string mail { get; set; }
        public string esadi { get; set; }
        public Nullable<System.DateTime> esdogum { get; set; }
        public Nullable<System.DateTime> evliliktarih { get; set; }
        public string spor { get; set; }
        public string takimi { get; set; }
        public string evhayvani { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    
        public virtual tbl_firma tbl_firma { get; set; }
    }
}
