//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sikayet_gelen
    {
        public int sikayetno { get; set; }
        public string sikayettipi { get; set; }
        public string iadedurum { get; set; }
        public Nullable<System.DateTime> sikayettarih { get; set; }
        public string firmakod { get; set; }
        public string kisikod { get; set; }
        public string personelkodu { get; set; }
        public string urunkod { get; set; }
        public int siparisno { get; set; }
        public Nullable<System.DateTime> teslimtarih { get; set; }
        public double toplamadet { get; set; }
        public int sevkiyatno { get; set; }
        public double sevkadet { get; set; }
        public string irsaliyeno { get; set; }
        public long sevkno { get; set; }
        public string aciklama { get; set; }
        public string dofkod { get; set; }
        public Nullable<System.DateTime> iadetarihi { get; set; }
        public string musterisikayetno { get; set; }
        public double zarartutari { get; set; }
        public string resim { get; set; }
        public bool bedelsiz { get; set; }
        public string acik { get; set; }
        public string degerlendirme { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
