//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel_bilgisayar
    {
        public long bilid { get; set; }
        public string personelkodu { get; set; }
        public string adi { get; set; }
        public string cinsi { get; set; }
        public string seviye { get; set; }
        public string aciklama { get; set; }
    }
}
