//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_islem_urun
    {
        public int makinaislemkod { get; set; }
        public string urunkod { get; set; }
        public bool enibelli { get; set; }
        public bool boyubelli { get; set; }
        public bool enibelirsiz { get; set; }
        public bool boyubelirsiz { get; set; }
        public double artien { get; set; }
        public double artiboy { get; set; }
        public double artitopen { get; set; }
        public double artitopboy { get; set; }
        public double yogunlukgram { get; set; }
        public double yogunlukadet { get; set; }
        public double yogunlukalan { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
