//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_klise_film
    {
        public int siparisno { get; set; }
        public string urunkod { get; set; }
        public string revizyonkod { get; set; }
        public double siparismiktar { get; set; }
        public string birimkod { get; set; }
        public System.DateTime siparistarih { get; set; }
        public string siparisbirim { get; set; }
        public double siparisfiyat { get; set; }
        public string dovizkod { get; set; }
        public string firmakod { get; set; }
        public string kisikod { get; set; }
        public string ozelbilgi { get; set; }
        public Nullable<double> bicakfiyat { get; set; }
        public string bdovizkod { get; set; }
        public Nullable<double> klisefiyat { get; set; }
        public string kdovizkod { get; set; }
        public Nullable<short> kliseadet { get; set; }
        public Nullable<bool> bfaturaet { get; set; }
        public Nullable<bool> kfaturaet { get; set; }
        public Nullable<bool> kontrol_kapat { get; set; }
        public Nullable<System.DateTime> kapattarih { get; set; }
        public Nullable<bool> kontrol_depo { get; set; }
        public Nullable<double> toplamalan { get; set; }
        public Nullable<double> toplamagirlik { get; set; }
        public Nullable<double> toplamadet { get; set; }
        public Nullable<double> toplamteslimmiktar { get; set; }
        public string personelkodu { get; set; }
        public Nullable<bool> imalattakip { get; set; }
        public Nullable<int> tramyogunlugu { get; set; }
        public Nullable<double> malzemetutar { get; set; }
        public Nullable<double> makinatutar { get; set; }
        public Nullable<double> genelgidertutar { get; set; }
        public Nullable<double> ekstragidertutar { get; set; }
        public Nullable<double> toplamteslim { get; set; }
        public Nullable<System.DateTime> muhtemeltarih { get; set; }
        public Nullable<System.DateTime> planlanantarih { get; set; }
        public Nullable<bool> depodan { get; set; }
        public Nullable<bool> ilkdefa { get; set; }
        public string ilkdefauy { get; set; }
        public Nullable<bool> revizyonvar { get; set; }
        public Nullable<bool> eskifilmat { get; set; }
        public Nullable<bool> revizyonfilmdegil { get; set; }
        public string revizyonnot { get; set; }
        public string irsaliyenot { get; set; }
        public string faturanot { get; set; }
        public string musterisano { get; set; }
        public string onayadres { get; set; }
        public string oncekilot { get; set; }
        public Nullable<bool> iptal { get; set; }
        public Nullable<bool> prova { get; set; }
        public Nullable<float> globalfiyat { get; set; }
        public string yeniurun { get; set; }
        public string urunacildi { get; set; }
        public Nullable<double> satistltutar { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string ek5 { get; set; }
        public string ek6 { get; set; }
        public string ek7 { get; set; }
        public string ek8 { get; set; }
        public string ek9 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
