//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mamul_tip
    {
        public int mamultipkod { get; set; }
        public string kodaciklama { get; set; }
        public byte hatsayisi { get; set; }
        public string cokyaprak { get; set; }
        public string cilt { get; set; }
        public string cesit { get; set; }
        public string anatip { get; set; }
        public double minimumaaaralik { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
