//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_randevu
    {
        public long randevuno { get; set; }
        public long gorid { get; set; }
        public string firmakod { get; set; }
        public System.DateTime randevutarihi { get; set; }
        public string bas_saat { get; set; }
        public string personelkodu { get; set; }
        public string sure { get; set; }
        public string randevu_saat { get; set; }
        public int gorusmeno { get; set; }
        public string bilgi { get; set; }
        public string gorusmetipno { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
