//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_disli_hesap
    {
        public string dislisayisi { get; set; }
        public string dislisayisi2 { get; set; }
        public string dislisayisi3 { get; set; }
        public short aaadet { get; set; }
        public float boy { get; set; }
        public Nullable<float> cevre { get; set; }
        public double dislidegeri { get; set; }
    }
}
