//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_teslimat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_firma_teslimat()
        {
            this.tbl_firma_teslimat_etiket = new HashSet<tbl_firma_teslimat_etiket>();
        }
    
        public long firmateslimatid { get; set; }
        public string firmakod { get; set; }
        public string subekod { get; set; }
        public string subead { get; set; }
        public string teslimatadres1 { get; set; }
        public string teslimatadres2 { get; set; }
        public string postakod { get; set; }
        public string ilcekod { get; set; }
        public string ilkod { get; set; }
        public string ulkekod { get; set; }
        public string telefon1 { get; set; }
        public string telefon2 { get; set; }
        public string faks1 { get; set; }
        public string faks2 { get; set; }
        public string mail { get; set; }
        public string web { get; set; }
        public string vergidairesi { get; set; }
        public string vergino { get; set; }
        public string tckimlikno { get; set; }
        public bool kullanilmiyor { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    
        public virtual tbl_firma tbl_firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_firma_teslimat_etiket> tbl_firma_teslimat_etiket { get; set; }
    }
}
