//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_firma
    {
        public long urunfirmaid { get; set; }
        public string urunkod { get; set; }
        public string firmakod { get; set; }
        public int maliyetkodu { get; set; }
        public short urunno { get; set; }
        public string urunfaturaadi { get; set; }
        public string urunmusterikod { get; set; }
        public string uruncesidi { get; set; }
    }
}
