//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_makina
    {
        public long urunislemid { get; set; }
        public string urunkod { get; set; }
        public string islemkod { get; set; }
        public short sira { get; set; }
        public string makinakodu { get; set; }
        public short ekgecis { get; set; }
        public short artisetupsure { get; set; }
        public double artisaattehiz { get; set; }
        public double dislidegeri { get; set; }
        public string dislisayisi { get; set; }
        public short aaadet { get; set; }
        public short yyadet { get; set; }
        public short islemsayisi { get; set; }
        public string aciklama { get; set; }
    }
}
