//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_klise_yenileme
    {
        public string klisekod { get; set; }
        public string yenilemeno { get; set; }
        public string klisetipkod { get; set; }
        public Nullable<System.DateTime> imaltarihi { get; set; }
        public bool iptal { get; set; }
        public Nullable<System.DateTime> imhatarihi { get; set; }
        public int tursayisi { get; set; }
        public double fiyat { get; set; }
        public double birimfiyat { get; set; }
        public string birimdovizkod { get; set; }
        public string klisesebepkod { get; set; }
        public string durumkod { get; set; }
        public string firmakod { get; set; }
        public bool sipariste { get; set; }
        public bool kullanimda { get; set; }
        public string imhasebepkod { get; set; }
        public string isteyen { get; set; }
        public string sebepkisi { get; set; }
        public string siparisno { get; set; }
        public string aciklama { get; set; }
        public double miktar1 { get; set; }
        public double miktar2 { get; set; }
        public double netmiktar { get; set; }
        public long said { get; set; }
        public int sasiparisno { get; set; }
        public string sira { get; set; }
        public string klisetakip { get; set; }
        public string teslimalan { get; set; }
        public Nullable<System.DateTime> teslimtarihi { get; set; }
        public Nullable<System.DateTime> gondertarihi { get; set; }
        public string uretimyeri { get; set; }
        public bool cekirdekvar { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
