//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_malzeme
    {
        public long maliyetmalzemeid { get; set; }
        public long maliyetkodu { get; set; }
        public int sira { get; set; }
        public string yapisalkod { get; set; }
        public string urunkod { get; set; }
        public string urunbirimkod { get; set; }
        public long maliyetislemid { get; set; }
        public bool hammadde { get; set; }
        public double gramaj { get; set; }
        public double hammaddefiyat { get; set; }
        public string parabirimi { get; set; }
        public double fiyateurokg { get; set; }
        public double fiyateuroalan { get; set; }
        public double malzemeuretimeni { get; set; }
    }
}
