//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vardiya_urun
    {
        public int vardiyano { get; set; }
        public int vardiyaaltno { get; set; }
        public string urunkod { get; set; }
        public double depocikis { get; set; }
        public double depoiade { get; set; }
        public bool depoiadekontrol { get; set; }
        public double deviralinan { get; set; }
        public double devirverilen { get; set; }
        public double sarfiyat { get; set; }
        public double harcanan { get; set; }
        public double netharcanan { get; set; }
        public double toplamadet { get; set; }
        public string birimkod { get; set; }
        public string personelkodu { get; set; }
        public bool hammadde { get; set; }
        public int hareketno { get; set; }
        public short sira { get; set; }
        public short birlesikadet { get; set; }
        public bool kullanildi { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
