//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grafik_onay
    {
        public long grafno { get; set; }
        public long grafikno { get; set; }
        public Nullable<System.DateTime> gidistarih { get; set; }
        public Nullable<System.DateTime> gelistarih { get; set; }
        public string grafikislemkod { get; set; }
        public string aciklama { get; set; }
    }
}
