//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_islem
    {
        public long siparisislemid { get; set; }
        public long urunislemid { get; set; }
        public int siparisno { get; set; }
        public long siparismakinaid { get; set; }
        public string islemkod { get; set; }
        public string dislisayisi { get; set; }
        public double dislidegeri { get; set; }
        public short aaadet { get; set; }
        public short yyadet { get; set; }
        public short islemsayisi { get; set; }
    }
}
