//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sevk
    {
        public long sevkno { get; set; }
        public string belgetipi { get; set; }
        public string durumu { get; set; }
        public string belgeserino { get; set; }
        public string belgesirano { get; set; }
        public long faturasevkno { get; set; }
        public short firmId { get; set; }
        public string firmakod { get; set; }
        public string carikod { get; set; }
        public string ilgilikod { get; set; }
        public string subekod { get; set; }
        public string musterisano { get; set; }
        public string sevkiyatkod { get; set; }
        public Nullable<System.DateTime> belgetarih { get; set; }
        public Nullable<System.DateTime> sevktarih { get; set; }
        public string sevkiyatnotu { get; set; }
        public string aciklama { get; set; }
        public int konsinyeno { get; set; }
        public short vade { get; set; }
        public string belgedovizkod { get; set; }
        public double faturakur { get; set; }
        public double iskontoyuzde { get; set; }
        public double iskontotutar { get; set; }
        public double toplam { get; set; }
        public double kdv { get; set; }
        public double yekun { get; set; }
        public string yaziyla { get; set; }
        public string iptal { get; set; }
        public string sevktipkod { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
