//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_birim
    {
        public int birimno { get; set; }
        public string urunkod { get; set; }
        public string birimkod { get; set; }
        public string ekbirimkod { get; set; }
        public double miktar { get; set; }
        public double ekmiktar { get; set; }
        public double birimoran { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
