//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_bakim_hareket
    {
        public int bakimhareketno { get; set; }
        public int bakimno { get; set; }
        public string stokkod { get; set; }
        public string urunkod { get; set; }
        public double miktar { get; set; }
        public double fiyat { get; set; }
    }
}
