//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_hareket
    {
        public int siparisno { get; set; }
        public string urunkod { get; set; }
        public long urunihtiyacid { get; set; }
        public int hareketno { get; set; }
        public double harcananhareket { get; set; }
        public double bitishareket { get; set; }
        public double toplammiktar2 { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
