//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun
    {
        public string urunkod { get; set; }
        public string revizyonkod { get; set; }
        public string uruntipkod { get; set; }
        public string musterikod { get; set; }
        public string mamultip { get; set; }
        public int mamultipkod { get; set; }
        public string slevetip { get; set; }
        public string urunadi { get; set; }
        public string urunfaturaadi { get; set; }
        public string urunadiIngilizce { get; set; }
        public string spekkod { get; set; }
        public string birimkod { get; set; }
        public double tekebadboy { get; set; }
        public double tekebaden { get; set; }
        public double tekebadyukseklik { get; set; }
        public short yyadet { get; set; }
        public double aabosluk { get; set; }
        public double yybosluk { get; set; }
        public short yybitisikadet { get; set; }
        public double baskiaabosluk { get; set; }
        public double lf { get; set; }
        public double yapistirmapayi { get; set; }
        public double cl { get; set; }
        public string malzemekod { get; set; }
        public bool malzemezorunlu { get; set; }
        public string malzemekod2 { get; set; }
        public short malzemeek { get; set; }
        public short bicakek { get; set; }
        public short makinaek { get; set; }
        public string kliseno { get; set; }
        public string yapiskankod { get; set; }
        public string tasiyicikod { get; set; }
        public string laminasyoncinsi { get; set; }
        public string bicakkodu { get; set; }
        public double minstok { get; set; }
        public double maxstok { get; set; }
        public double siparismiktar { get; set; }
        public string muhasebekod { get; set; }
        public string urunnot { get; set; }
        public string imalatcikod { get; set; }
        public bool adettakim { get; set; }
        public short takimmiktar { get; set; }
        public string rulobirim { get; set; }
        public bool adettakim2 { get; set; }
        public short takimmiktar2 { get; set; }
        public string yarimamulkod { get; set; }
        public string kullanimalanikod { get; set; }
        public string yapisalkod1 { get; set; }
        public string yapisalkod2 { get; set; }
        public string yapisalkod3 { get; set; }
        public string opaklikkod { get; set; }
        public string parlaklikkod { get; set; }
        public string cekeryuzde { get; set; }
        public double yogunluk { get; set; }
        public short kalinlik { get; set; }
        public double gramaj { get; set; }
        public double gramajbutun { get; set; }
        public string paketmiktar { get; set; }
        public string paketbirimkod { get; set; }
        public string iccap { get; set; }
        public double fiyat { get; set; }
        public double maliyetfiyat { get; set; }
        public double acilisfiyat { get; set; }
        public string uretimonay { get; set; }
        public Nullable<System.DateTime> uretimonaytarih { get; set; }
        public string uretimpersonel { get; set; }
        public string grafikonay { get; set; }
        public Nullable<System.DateTime> grafikonaytarih { get; set; }
        public string grafikpersonel { get; set; }
        public double alan { get; set; }
        public double agirlik { get; set; }
        public bool ambalaj { get; set; }
        public double depolama { get; set; }
        public string sabagkod { get; set; }
        public int maliyetkodu { get; set; }
        public double adetagirlik { get; set; }
        public double adeten { get; set; }
        public double adetboy { get; set; }
        public string genelkod { get; set; }
        public string firmakod { get; set; }
        public string maliyetbirimkod { get; set; }
        public string imalatkod { get; set; }
        public string imalatadi { get; set; }
        public string baskitipkod { get; set; }
        public string eskiurunkod { get; set; }
        public bool urunkullanilmiyor { get; set; }
        public double uruneken { get; set; }
        public double tasiyicieken { get; set; }
        public string gidergrupkod { get; set; }
        public double konsinyemiktar { get; set; }
        public double konsinyealan { get; set; }
        public Nullable<System.DateTime> konsinyetarih { get; set; }
        public string hammaddefiyatbirimi { get; set; }
        public string resim { get; set; }
        public Nullable<System.DateTime> resimtarihi { get; set; }
        public string uygulamasekli { get; set; }
        public string holtmelt { get; set; }
        public string perfore { get; set; }
        public bool devamlilik { get; set; }
        public string arsivno { get; set; }
        public string boyayogunluk { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
