//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sevk_alt
    {
        public long satirno { get; set; }
        public long sevkno { get; set; }
        public byte sirano { get; set; }
        public int siparisno { get; set; }
        public string musterisano { get; set; }
        public string urunkod { get; set; }
        public short urunno { get; set; }
        public string birimkod { get; set; }
        public int sevkiyatno { get; set; }
        public string stokkod { get; set; }
        public long urunsevkdetayid { get; set; }
        public int koliadet { get; set; }
        public int ruloadet { get; set; }
        public string urunadet { get; set; }
        public double toplamadet { get; set; }
        public double siparisfiyat { get; set; }
        public string siparisdovizkod { get; set; }
        public double kur { get; set; }
        public double sabitkur { get; set; }
        public string dovizalissatis { get; set; }
        public double faturafiyat { get; set; }
        public double iskontoyuzde { get; set; }
        public double iskontotutar { get; set; }
        public double tutar { get; set; }
        public double kdv { get; set; }
        public double kdvtutar { get; set; }
        public double kdvlitutar { get; set; }
        public string aciklama { get; set; }
        public bool onaysiz { get; set; }
    }
}
