//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teklif_fiyat
    {
        public long kodu { get; set; }
        public string sirano { get; set; }
        public string gonderkodu { get; set; }
        public int gonderno { get; set; }
        public int maliyetkodu { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public double adet { get; set; }
        public double minadet { get; set; }
        public double maxadet { get; set; }
        public double klisemasraf { get; set; }
        public double bicakmasraf { get; set; }
        public string urunnot { get; set; }
        public string urunnot2 { get; set; }
        public string teklifbirimi { get; set; }
        public double globalfiyat { get; set; }
        public bool toplamfiyat { get; set; }
        public double toplamfiyattutar { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
