//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_test
    {
        public string testtipi { get; set; }
        public int minadet { get; set; }
        public int maxadet { get; set; }
        public int minmetre { get; set; }
        public int maxmetre { get; set; }
        public short numuneadet { get; set; }
    }
}
