//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet_islem
    {
        public long maliyetislemid { get; set; }
        public int maliyetkodu { get; set; }
        public short ekgecis { get; set; }
        public byte sira { get; set; }
        public string takipadi { get; set; }
        public string islemkod { get; set; }
        public string islemtipkod { get; set; }
        public string makinakodu { get; set; }
        public short islemtekrari { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public string birimkod { get; set; }
        public string ekstragideradi { get; set; }
        public string ektragiderbirim { get; set; }
        public double ekstragiderfiyat { get; set; }
        public string ektradovizkod { get; set; }
        public string dislisayisi { get; set; }
        public short aaadet { get; set; }
        public short yyadet { get; set; }
        public float dislidegeri { get; set; }
        public double yuzdefire { get; set; }
        public double setupfire { get; set; }
        public string aciklama { get; set; }
        public double setupfiyat { get; set; }
        public string setupdovizkod { get; set; }
        public double artisaattehiz { get; set; }
        public double boyabirimfiyat { get; set; }
        public string boyadovizkod { get; set; }
        public double boyayogunlugu { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
