//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_stokkart
    {
        public long stokid { get; set; }
        public string stokkod { get; set; }
        public string uruntipkod { get; set; }
        public string urunkod { get; set; }
        public short urunno { get; set; }
        public string firmakod { get; set; }
        public double miktar1 { get; set; }
        public double miktar2 { get; set; }
        public int tabaka { get; set; }
        public double netmiktar { get; set; }
        public string birimkod { get; set; }
        public double stokgramaji { get; set; }
        public System.DateTime tarih { get; set; }
        public string kagittipi { get; set; }
        public string setmi { get; set; }
        public double tabakaboy { get; set; }
        public string depokod { get; set; }
        public string aciklama { get; set; }
        public string uyarinotu { get; set; }
        public int sevkiyatno { get; set; }
        public int sevkiyatno2 { get; set; }
        public int koliadet { get; set; }
        public int ruloadet { get; set; }
        public string urunadet { get; set; }
        public double toplamadet { get; set; }
        public string rafkodu { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public double fiyattl { get; set; }
        public int siparisno { get; set; }
        public string gideceksiparisno { get; set; }
        public string giriskkno { get; set; }
        public int teslimno { get; set; }
        public string kkpersonelkodu { get; set; }
        public string dosyano { get; set; }
        public double sevkbekleyenmiktar { get; set; }
        public string faturaedildi { get; set; }
        public long faturasevkno { get; set; }
        public string sarfedildi { get; set; }
        public long sikayetno { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
