//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bicak
    {
        public long bicakId { get; set; }
        public string bicakkodu { get; set; }
        public string bicakuzunkod { get; set; }
        public string kisakod { get; set; }
        public string bicakno { get; set; }
        public string arsivno { get; set; }
        public bool bicakyonu { get; set; }
        public string dislisayisi { get; set; }
        public double tekebadboy { get; set; }
        public double tekebaden { get; set; }
        public short aaadet { get; set; }
        public short yyadet { get; set; }
        public float radus { get; set; }
        public string bicaktipkod { get; set; }
        public double aabosluk { get; set; }
        public double yybosluk { get; set; }
        public short yybitisikadet { get; set; }
        public string ozelbilgi { get; set; }
        public string firmakod { get; set; }
        public string urunkod { get; set; }
        public short bicakek { get; set; }
        public string grafikonay { get; set; }
        public string kullanimalanikod { get; set; }
        public string bicakiz { get; set; }
        public Nullable<System.DateTime> bicakiztarihi { get; set; }
        public string sabagkod { get; set; }
        public int bicaksekilkod { get; set; }
        public string ds { get; set; }
        public string yenibicak { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public Nullable<System.DateTime> olusturmatarihi { get; set; }
    }
}
