//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_disli
    {
        public string makinakodu { get; set; }
        public string islemkod { get; set; }
        public string dislisayisi { get; set; }
        public string dislisayisi2 { get; set; }
        public string dislisayisi3 { get; set; }
        public float dislidegeri { get; set; }
        public short islemunitesayisi { get; set; }
        public double manyetiken { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
