//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_teslimat_etiket
    {
        public int firmaEtiketId { get; set; }
        public string firmakod { get; set; }
        public string subekod { get; set; }
        public string etikettipi { get; set; }
    
        public virtual tbl_firma_teslimat tbl_firma_teslimat { get; set; }
    }
}
