//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sa_siparis_siparis
    {
        public long sasaid { get; set; }
        public int said { get; set; }
        public int sasiparisno { get; set; }
        public string sira { get; set; }
        public int siparisno { get; set; }
        public long sipihtiyacid { get; set; }
    }
}
