//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_gider
    {
        public int siparisno { get; set; }
        public string giderkod { get; set; }
        public string urunkod { get; set; }
        public string makinakodu { get; set; }
        public double fiyat { get; set; }
        public double miktar { get; set; }
        public double tutar { get; set; }
        public string dovizkod { get; set; }
        public double kur { get; set; }
        public string planurunkod { get; set; }
        public double planlananfiyat { get; set; }
        public double planlananmiktar { get; set; }
        public double planlanantutar { get; set; }
        public string planlanandovizkod { get; set; }
        public double planlanankur { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
