//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_ambalaji
    {
        public string urunkod { get; set; }
        public Nullable<float> en { get; set; }
        public Nullable<float> boy { get; set; }
        public Nullable<float> yuk { get; set; }
        public Nullable<float> hacim { get; set; }
        public Nullable<float> agirlik { get; set; }
        public Nullable<float> miktar { get; set; }
    }
}
