//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_ihtiyac
    {
        public long urunihtiyacid { get; set; }
        public string urunkod { get; set; }
        public string firmakod { get; set; }
        public string ambalajkod { get; set; }
        public double adetoran { get; set; }
        public double alanoran { get; set; }
        public double agirlikoran { get; set; }
        public double urunoran { get; set; }
        public double ambalajoran { get; set; }
        public string urunbirimtip { get; set; }
        public string ambalajbirimkod { get; set; }
        public bool siparisaktar { get; set; }
        public bool ambalaj { get; set; }
        public bool eni { get; set; }
        public double en { get; set; }
        public bool hammadde { get; set; }
        public long urunislemid { get; set; }
        public string islemkod { get; set; }
        public string aciklama { get; set; }
        public long urunmalzemeid { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
