//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_birim
    {
        public string birimkod { get; set; }
        public string kodaciklama { get; set; }
        public string birimtip { get; set; }
        public double oran { get; set; }
        public string simge { get; set; }
        public string teklifbirimikullan { get; set; }
        public string kodaciklamaing { get; set; }
        public string simgeing { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
