//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_kk
    {
        public string urunkod { get; set; }
        public short sira { get; set; }
        public short iccap { get; set; }
        public short discap { get; set; }
        public int bobindeadet { get; set; }
        public string bobindebirim { get; set; }
        public string akisyonu { get; set; }
        public short musteriyyadet { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
