//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_siparis_klise_alt
    {
        public long sipariskliseid { get; set; }
        public long siparisno { get; set; }
        public string kliseno { get; set; }
        public string klisekod { get; set; }
        public string no { get; set; }
        public string revizyonkod { get; set; }
        public string baskitipkod { get; set; }
        public string klisetipkod { get; set; }
        public string makinakodu { get; set; }
        public string dislisayisi { get; set; }
        public short aaadet { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
