//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kalite_son
    {
        public int kalitesonno { get; set; }
        public Nullable<int> siparisno { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<float> miktar { get; set; }
        public string irsaliyeno { get; set; }
        public string sano { get; set; }
        public Nullable<int> urunrulo { get; set; }
        public Nullable<int> urunbirim { get; set; }
        public Nullable<int> ornekrulo { get; set; }
        public Nullable<int> ornekbirim { get; set; }
        public string kabul { get; set; }
        public string dusunceler { get; set; }
        public string sonuc0 { get; set; }
        public string sonuc1 { get; set; }
        public string sonuc2 { get; set; }
        public string sonuc3 { get; set; }
        public string sonuc4 { get; set; }
        public string sonuc5 { get; set; }
        public string sonuc6 { get; set; }
        public string sonuc7 { get; set; }
        public string sonuc8 { get; set; }
        public string sonuc9 { get; set; }
        public string sonuc10 { get; set; }
        public string sonuc11 { get; set; }
        public string sonuc12 { get; set; }
        public string sonuc13 { get; set; }
        public string sonuc14 { get; set; }
        public string sonuc15 { get; set; }
        public string aql0 { get; set; }
        public string aql1 { get; set; }
        public string aql2 { get; set; }
        public string aql3 { get; set; }
        public string aql4 { get; set; }
        public string aql5 { get; set; }
        public string aql6 { get; set; }
        public string aql7 { get; set; }
        public string aql8 { get; set; }
        public string aql9 { get; set; }
        public string aql10 { get; set; }
        public string aql11 { get; set; }
        public string aql12 { get; set; }
        public string aql13 { get; set; }
        public string aql14 { get; set; }
        public string aql15 { get; set; }
        public string kritik { get; set; }
        public string minor { get; set; }
        public string major { get; set; }
        public string aqlkritik { get; set; }
        public string aqlminor { get; set; }
        public string aqlmajor { get; set; }
        public string standart0 { get; set; }
        public Nullable<float> standart1 { get; set; }
        public Nullable<float> standart2 { get; set; }
        public Nullable<float> standart3 { get; set; }
        public string standart4 { get; set; }
        public Nullable<float> standart5 { get; set; }
        public string standart6 { get; set; }
        public string standart7 { get; set; }
        public string standart8 { get; set; }
        public Nullable<float> standart9 { get; set; }
        public string bulgu0 { get; set; }
        public Nullable<float> bulgu1 { get; set; }
        public Nullable<float> bulgu2 { get; set; }
        public Nullable<float> bulgu3 { get; set; }
        public string bulgu4 { get; set; }
        public Nullable<float> bulgu5 { get; set; }
        public string bulgu6 { get; set; }
        public string bulgu7 { get; set; }
        public string bulgu8 { get; set; }
        public Nullable<float> bulgu9 { get; set; }
        public string renk0 { get; set; }
        public string renk1 { get; set; }
        public string renk2 { get; set; }
        public string renk3 { get; set; }
        public string renk4 { get; set; }
        public string renk5 { get; set; }
        public string renk6 { get; set; }
        public string renk7 { get; set; }
        public string personelkodu { get; set; }
        public string musteripartino { get; set; }
        public bool paketleme { get; set; }
    }
}
