//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_sevk_detay_alt
    {
        public long urunsevkaltid { get; set; }
        public long urunsevkdetayid { get; set; }
        public long urunsevkid { get; set; }
        public string stokkod { get; set; }
        public long siparisno { get; set; }
        public string takimtek { get; set; }
        public string setmi { get; set; }
        public string firmakod { get; set; }
        public string subekod { get; set; }
        public string urunkod { get; set; }
        public short urunno { get; set; }
        public double sevkmiktar { get; set; }
        public double agirlik { get; set; }
        public string belgekesildi { get; set; }
        public string belgetipi { get; set; }
        public double yenifiyat { get; set; }
        public string birimkod { get; set; }
        public bool onaysiz { get; set; }
    }
}
