//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_firma_kontakt_cocuk
    {
        public string firmakod { get; set; }
        public string kisikod { get; set; }
        public string cocukadi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string bilgi { get; set; }
        public Nullable<int> hatirno { get; set; }
    }
}
