//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tanim
    {
        public int TID { get; set; }
        public string Tanim { get; set; }
        public string Aciklama { get; set; }
        public string Tip { get; set; }
        public Nullable<int> TipInt { get; set; }
    }
}
