//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_makina_kart
    {
        public string makinakodu { get; set; }
        public string makinaadi { get; set; }
        public double maksboy { get; set; }
        public double minboy { get; set; }
        public double maksen { get; set; }
        public double minen { get; set; }
        public short makinaek { get; set; }
        public double genelgiderpayi { get; set; }
        public double iscilikgideri { get; set; }
        public double elektrikgideri { get; set; }
        public double giderkatsayisi { get; set; }
        public double saatucret { get; set; }
        public double setup { get; set; }
        public double setupfire { get; set; }
        public double yuzdefire { get; set; }
        public string durumkod { get; set; }
        public bool aktif { get; set; }
        public byte uretimplanlamaadet { get; set; }
        public byte planlamasirasi { get; set; }
        public bool kkontrol { get; set; }
        public short bakiunitesi { get; set; }
        public string anaislemkod { get; set; }
        public double gidersaatucret { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
