//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bicak_tip
    {
        public string bicaktipkod { get; set; }
        public string kodaciklama { get; set; }
        public string simge { get; set; }
        public bool dislivar { get; set; }
        public bool dislisizvar { get; set; }
        public bool yandondur { get; set; }
        public double dislidegeri { get; set; }
        public double maksboy { get; set; }
        public double minboy { get; set; }
        public double maksen { get; set; }
        public double minen { get; set; }
        public double fiyat { get; set; }
        public string dovizkod { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
