//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_anilox
    {
        public string aniloxkod { get; set; }
        public string kodaciklama { get; set; }
        public string makinakodu { get; set; }
        public int linecm { get; set; }
        public int lineinch { get; set; }
        public double volume { get; set; }
        public double boyaaktarimi { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
