//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_maliyet
    {
        public long maliyetkodu { get; set; }
        public string firmakod { get; set; }
        public double maliyeten { get; set; }
        public double maliyetboy { get; set; }
        public double maliyetadet { get; set; }
        public byte maliyetrenk { get; set; }
        public int mamultipkod { get; set; }
        public string slevetip { get; set; }
        public bool bicak_var { get; set; }
        public bool yenibicak { get; set; }
        public bool baski_var { get; set; }
        public byte renk { get; set; }
        public string makinakodu { get; set; }
        public string makinakodub { get; set; }
        public short bicakek { get; set; }
        public short malzemeek { get; set; }
        public short makinaek { get; set; }
        public string bicakkodu { get; set; }
        public double tekebadboy { get; set; }
        public double tekebaden { get; set; }
        public double tekebadyukseklik { get; set; }
        public short yyadet { get; set; }
        public double aabosluk { get; set; }
        public double yybosluk { get; set; }
        public short yybitisikadet { get; set; }
        public short musteriyyadet { get; set; }
        public double lf { get; set; }
        public double cl { get; set; }
        public double netenverimi { get; set; }
        public double enverimi { get; set; }
        public bool bicakmasraf_ekle { get; set; }
        public double bicakmasraf { get; set; }
        public bool klisemasraf_ekle { get; set; }
        public double klisetutar { get; set; }
        public string malzemecinsi { get; set; }
        public bool malzemecinsi_ekle { get; set; }
        public double malzemefiyat { get; set; }
        public double gramaj { get; set; }
        public double kalinlik { get; set; }
        public double yogunluk { get; set; }
        public string malzemecinsi2 { get; set; }
        public bool malzemecinsi_ekle2 { get; set; }
        public double malzemefiyat2 { get; set; }
        public double gramaj2 { get; set; }
        public bool vade_ekle { get; set; }
        public short vade { get; set; }
        public float vadevalor { get; set; }
        public bool boyayogunlugu_ekle { get; set; }
        public string boyayogunluk { get; set; }
        public double boyafiyat { get; set; }
        public bool laminasyoncinsi_ekle { get; set; }
        public string laminasyonadi { get; set; }
        public double genelgidereur { get; set; }
        public double genelgider { get; set; }
        public double yonetimgideri { get; set; }
        public string urunadi { get; set; }
        public string urunkod { get; set; }
        public string ozelbilgi { get; set; }
        public string onayagonderen { get; set; }
        public Nullable<System.DateTime> onayagondertarih { get; set; }
        public string kontrol_maliyet { get; set; }
        public bool durum_kontrol { get; set; }
        public string teklifbirimi { get; set; }
        public string birimkod { get; set; }
        public bool baskibicakayri { get; set; }
        public string bicaktipkod { get; set; }
        public bool adettakim { get; set; }
        public short takimmiktar { get; set; }
        public string rulobirim { get; set; }
        public bool adettakim2 { get; set; }
        public short takimmiktar2 { get; set; }
        public short takimuretimmiktar { get; set; }
        public double depolama { get; set; }
        public string uruntipkod { get; set; }
        public string dovizkod { get; set; }
        public bool ribon { get; set; }
        public string musterikod { get; set; }
        public string onayliyan { get; set; }
        public Nullable<System.DateTime> onaytarih { get; set; }
        public double uruneken { get; set; }
        public double maliyeteken { get; set; }
        public float baglamaucreti { get; set; }
        public string baglamaparabirimi { get; set; }
        public bool baglamafaturaet { get; set; }
        public string urunbirimtip { get; set; }
        public double alannet { get; set; }
        public double alan { get; set; }
        public double agirliknet { get; set; }
        public double agirlik { get; set; }
        public string tipi { get; set; }
        public string hammaddefiyatbirimi { get; set; }
        public string uygulamasekli { get; set; }
        public string yaldiz { get; set; }
        public string holtmelt { get; set; }
        public string perfore { get; set; }
        public string laminasyon { get; set; }
        public string acan { get; set; }
        public string rpt { get; set; }
        public byte cesit { get; set; }
        public byte montaj { get; set; }
        public double yapistirmapayi { get; set; }
        public bool devamlilik { get; set; }
        public bool ortfiyatvar { get; set; }
        public Nullable<System.DateTime> fiyattarih { get; set; }
        public double eurokur { get; set; }
        public double dolarkur { get; set; }
        public double eurobarite { get; set; }
        public double sabitkur { get; set; }
        public double genelgideryuzde { get; set; }
        public string ek1 { get; set; }
        public string ek2 { get; set; }
        public string ek3 { get; set; }
        public string ek4 { get; set; }
        public string ek5 { get; set; }
        public string ek6 { get; set; }
        public string olusturanadisoyadi { get; set; }
        public System.DateTime olusturmatarihi { get; set; }
    }
}
