//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfStandarWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vardiya_bicak
    {
        public int vardiyaaltno { get; set; }
        public string bicakkodu { get; set; }
        public string yenilemeno { get; set; }
        public int tursayisi { get; set; }
    }
}
