// <auto-generated />
using System;
using EfCoreBahis.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreBahis.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisCesit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BahisKonusuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<int?>("OynananId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("BahisKonusuId");

                    b.HasIndex("OynananId");

                    b.ToTable("BahisCesitleri");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisCesitDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BahisCesitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<double>("Oran")
                        .HasColumnType("float");

                    b.Property<int>("OynananId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("BahisCesitId");

                    b.HasIndex("OynananId");

                    b.ToTable("BahisCesitDetay");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BahisCesitDetayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<double>("OynananTutar")
                        .HasColumnType("float");

                    b.Property<int>("OynayanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("BahisCesitDetayId");

                    b.HasIndex("OynayanId");

                    b.ToTable("BahisHareketleri");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisKonusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Acikmi")
                        .HasColumnType("bit");

                    b.Property<string>("BahisAciklama")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<DateTime>("KapanisSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("BahisKonulari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acikmi = true,
                            BahisAciklama = "Derse Gec Kalma",
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(2587),
                            KapanisSaati = new DateTime(2022, 11, 16, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(2590)
                        });
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Kasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("ToplamBakiye")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("KasaAdi")
                        .IsUnique();

                    b.ToTable("Kasalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(5856),
                            KasaAdi = "TL Kasasi",
                            ToplamBakiye = 100000.0
                        });
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.KasaHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BahisCesitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<byte>("HareketTipi")
                        .HasColumnType("tinyint");

                    b.Property<int>("KasaId")
                        .HasColumnType("int");

                    b.Property<int>("OynayanId")
                        .HasColumnType("int");

                    b.Property<double>("Tutar")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("BahisCesitId");

                    b.HasIndex("KasaId");

                    b.HasIndex("OynayanId");

                    b.ToTable("KasaHareketleri");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Oynanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("BahisKonusuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<double>("Guc")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("BahisKonusuId");

                    b.ToTable("Oyanananlar");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Oynayan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double?>("Bakiye")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.HasKey("Id");

                    b.HasIndex("TcNo")
                        .IsUnique();

                    b.ToTable("Oynayanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Ali Yilmaz",
                            Bakiye = 1000.0,
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(9249),
                            TcNo = "123"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Ayse Kaya",
                            Bakiye = 1000.0,
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(9254),
                            TcNo = "124"
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Hasan Mert",
                            Bakiye = 1000.0,
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(9256),
                            TcNo = "125"
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Fatma Tasdemir",
                            Bakiye = 1000.0,
                            CreateDate = new DateTime(2022, 11, 15, 19, 46, 48, 826, DateTimeKind.Local).AddTicks(9259),
                            TcNo = "126"
                        });
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisCesit", b =>
                {
                    b.HasOne("EfCoreBahis.Entites.Concrete.BahisKonusu", "BahisKonusu")
                        .WithMany("BahisCesitleri")
                        .HasForeignKey("BahisKonusuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreBahis.Entites.Concrete.Oynanan", null)
                        .WithMany("BahisCesitleri")
                        .HasForeignKey("OynananId");

                    b.Navigation("BahisKonusu");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisCesitDetay", b =>
                {
                    b.HasOne("EfCoreBahis.Entites.Concrete.BahisCesit", "BahisCesit")
                        .WithMany()
                        .HasForeignKey("BahisCesitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreBahis.Entites.Concrete.Oynanan", "Oynanan")
                        .WithMany()
                        .HasForeignKey("OynananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BahisCesit");

                    b.Navigation("Oynanan");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisHareket", b =>
                {
                    b.HasOne("EfCoreBahis.Entites.Concrete.BahisCesitDetay", "BahisCesitDetay")
                        .WithMany()
                        .HasForeignKey("BahisCesitDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreBahis.Entites.Concrete.Oynayan", "Oynayan")
                        .WithMany()
                        .HasForeignKey("OynayanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BahisCesitDetay");

                    b.Navigation("Oynayan");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.KasaHareket", b =>
                {
                    b.HasOne("EfCoreBahis.Entites.Concrete.BahisCesit", "BahisCesit")
                        .WithMany()
                        .HasForeignKey("BahisCesitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreBahis.Entites.Concrete.Kasa", "Kasa")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreBahis.Entites.Concrete.Oynayan", "Oynayan")
                        .WithMany()
                        .HasForeignKey("OynayanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BahisCesit");

                    b.Navigation("Kasa");

                    b.Navigation("Oynayan");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Oynanan", b =>
                {
                    b.HasOne("EfCoreBahis.Entites.Concrete.BahisKonusu", null)
                        .WithMany("Oyuncular")
                        .HasForeignKey("BahisKonusuId");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.BahisKonusu", b =>
                {
                    b.Navigation("BahisCesitleri");

                    b.Navigation("Oyuncular");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Kasa", b =>
                {
                    b.Navigation("KasaHareketleri");
                });

            modelBuilder.Entity("EfCoreBahis.Entites.Concrete.Oynanan", b =>
                {
                    b.Navigation("BahisCesitleri");
                });
#pragma warning restore 612, 618
        }
    }
}
